# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AY9lQlrZifHU-vsmiUOlPPEIL5-fPSpA
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10,10,0.5)
a=3
b=5
print('x:{}, a:{}, b:{}'.format(x[:10],a,b))
y1=a*x+b
plt.plot(x,y1,'.')
plt.plot(x,y1)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('Plot of y = ax+b')
plt.grid(color = 'blue', linestyle = '--', linewidth = 0.5)
for i in range(0, len(x), 5):
   plt.annotate(f'({x[i]}, {y1[i]:.1f})', (x[i], y1[i]), textcoords="offset points", xytext=(-5,-10), ha='center')
plt.show()

a=5
b=10
print('x:{}, a:{}, b:{}'.format(x[:10],a,b))
x=np.arange(0,10,0.5)
sin=np.sin(x)
y = a * sin + b
plt.plot(x,y)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.xlim(-10,10)
plt.grid(color = 'blue', linestyle = '--', linewidth = 0.5)
plt.title('Plot of y = asin(x)+b')
for i in range(0, len(x), 5):
   plt.annotate(f'({x[i]}, {y[i]:.1f})', (x[i], y[i]), textcoords="offset points", xytext=(-5,-10), ha='center')
plt.show()