# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AY9lQlrZifHU-vsmiUOlPPEIL5-fPSpA

# Mam Class
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10,10,0.5)
a=3
b=5
print('x:{}, a:{}, b:{}'.format(x[:10],a,b))
y1=a*x+b
plt.plot(x,y1,'.')
plt.plot(x,y1)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('Plot of y = ax+b')
plt.grid(color = 'blue', linestyle = '--', linewidth = 0.5)
for i in range(0, len(x), 5):
   plt.annotate(f'({x[i]}, {y1[i]:.1f})', (x[i], y1[i]), textcoords="offset points", xytext=(-5,-10), ha='center')
plt.show()

a=5
b=10
print('x:{}, a:{}, b:{}'.format(x[:10],a,b))
x=np.arange(0,10,0.5)
sin=np.sin(x)
y = a * sin + b
plt.plot(x,y)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.xlim(-10,10)
plt.grid(color = 'blue', linestyle = '--', linewidth = 0.5)
plt.title('Plot of y = asin(x)+b')
for i in range(0, len(x), 5):
   plt.annotate(f'({x[i]}, {y[i]:.1f})', (x[i], y[i]), textcoords="offset points", xytext=(-5,-10), ha='center')
plt.show()

"""#practice

## matplotlib.annotate practice
"""

x = range(10, 61, 10)
y = range(1, 7)
print(list(zip(x,y)))

plt.bar(x, y, width=5)

plt.bar(x, y, width=5)
plt.annotate('min value', xy=(10,1))

plt.bar(x, y, width=5)
plt.annotate('min value', xy=(10,1), ha='center', va='bottom')

plt.bar(x, y, width=5)
plt.annotate('min value',
             xy=(10,1),
             ha='center',
             va='bottom',
             arrowprops={'facecolor':'red'},
             xytext=(15,3)
)

"""## Plot Practice"""

x = np.arange(-10, 10, 0.5)
a = 3
b = 5
print('x:{}, a:{}, b:{}'.format(x[:10], a, b))

y = a*x+b
plt.plot(x,y, '.')

plt.plot(x,y, '.')
plt.plot(x,y)

plt.plot(x,y, '.')
plt.plot(x,y)
plt.grid(color='blue', linestyle='--', linewidth=0.5)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('plot of: ax+b')

plt.plot(x,y, '.')
plt.plot(x,y)
plt.grid(color='blue', linestyle='--', linewidth=0.5)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('plot of: ax+b')
for i in range(0, len(x), 5):
  plt.annotate(f'{x[i]},{y[i]:.1f}', (x[i], y[i]))
plt.show()

plt.plot(x,y, '.')
plt.plot(x,y)
plt.grid(color='blue', linestyle='--', linewidth=0.5)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('plot of: ax+b')
for i in range(0, len(x), 5):
  plt.annotate(f'{x[i]},{y[i]:.1f}', (x[i], y[i]), textcoords='offset points', ha='center', xytext=(-5, -10))
plt.show()

a=5
b=5
x = np.arange(0, 10, 0.5)
y = a * np.sin(x)*10

print(list(zip(x,y)))

print(list(zip(x,y))[:5])

formattedOuput = [(f'{a:.1f},{b:.1f}') for a, b in zip(x, y)]
print(formattedOuput)

print(formattedOuput[:5])

plt.plot(x,y, '.')
plt.plot(x,y)
plt.grid(color='blue', linestyle='--', linewidth=0.5)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('plot of y=ax+c')
plt.xlim([0, 10])
for i in range(0, len(x), 2):
  plt.annotate(formattedOuput[i], (x[i], y[i]), ha='center', textcoords='offset points', xytext=(-5, -10))
plt.show()

plt.plot(x,y, '.')
plt.plot(x,y)
plt.grid(color='blue', linestyle='--', linewidth=0.5)
plt.xlabel('-->x')
plt.ylabel('-->y')
plt.title('plot of y=ax+c')
plt.xlim([0, 10])
for i in range(0, len(x), 0.5):
  plt.annotate(f'{formattedOuput[i]:.1f}')
plt.show()